# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - go test ./...

  install:
    desc: Compiles sri-fixer, and puts it in your go path. See `go env GOPATH` and check that your $PATH is set to include it if you're struggling to get sri-fixer installed
    cmds:
      - go install
      - echo "Installed! Call sri-fixer to use"
    silent: true
